* PLEASE DONATE
Developing and, more importantly, documenting the continuous scroll
functionality (and additionally discovering and reporting Emacs bugs) costs a
lot of time. Learning, and finding out how things work in Emacs and thinking
about how things should get implemented, with lots of trial and error, costs a
lot of time (although much of Emacs is well documented, the more exotic
functionalities and pdf-tools itself lack good documentation, slowing down
development by a factor of about 100. More specifically, simply implementing
continuous scroll was not that hard, but fixing features like displaying in
multiple buffers, isearch, pdf-occur, annotations etc., while all of those are
more or less undocumented, is a lot of work). I am investing all those, probably
hundreds of, hours to improve Emacs for everyone, hoping it will help to
increase Emacs its popularity, so that more users/students can enjoy its
elegance.

Although, if I could, I would be happy to do the work without asking for
donations, unfortunately my financial situation makes that impossible and
currently prevents me from further working on, and finishing, this feature.
Therefore, if you like this feature (if not for yourself, then maybe for others,
like e.g. students) then please consider to make a donation, so that I will be
able to continue my work on this package (probably by explaining its workings
first, see [[../../wiki][the wiki section]], so that more people can help fixing the bugs), or,
contribute by helping to fix remaining bugs/[[Incomplete features][incomplete features]].

* Incomplete features
- although /isearch/ seemed fully functional in commit [[https://github.com/dalanicolai/pdf-tools/commit/1fd1f98ac2a8ff2be8dc160f8a1056910b8ecac5][1fd1f98]], it got broken
  somewhere while fixing /occur/ functionality (which seems to work fine)
- latex sync does not work yet
- goto page usually works initially, but gets broken after some usage

* Installation
