(defun pdf-scroll-up ()
  (interactive)
  (let* ((image-height (cdr (pdf-view-image-size)))
         (scroll-range (/ image-height 20))
         (half-scroll-range (/ scroll-range 2)))
    (when (< (- image-height half-scroll-range)
             (set-window-vscroll nil (+ (window-vscroll nil t) scroll-range) t)
             (+ image-height half-scroll-range))
    ;; (when (< (print (- image-height half-scroll-range))
    ;;          (print (set-window-vscroll nil (+ (window-vscroll nil t) scroll-range) t))
    ;;          (print (+ image-height half-scroll-range)))
      (pdf-view-next-page)
      (set-window-vscroll nil 0 t))))

(defun pdf-scroll-down ()
  (interactive)
  (let* ((image-height (cdr (pdf-view-image-size)))
         (scroll-range (/ image-height 20))
         (half-scroll-range (/ scroll-range 2)))
    (when (<= 0
                    (set-window-vscroll nil (- (window-vscroll nil t) scroll-range) t)
                    (+  half-scroll-range))
    ;; (when (print (<= (print 0)
    ;;                  (print (set-window-vscroll nil (- (window-vscroll nil t) scroll-range) t))
    ;;                  (print (+  half-scroll-range))))
      (pdf-view-previous-page)
      (set-window-vscroll nil image-height t)
      (set-window-vscroll nil image-height t))))

;; (define-key global-map (kbd "C-j") nil)
;; (evil-define-key 'evilified pdf-view-mode-map (kbd "C-j") #'pdf-scroll-up)

;; (define-key global-map (kbd "C-k") nil)
;; (evil-define-key 'evilified pdf-view-mode-map (kbd "C-k") #'pdf-scroll-down)
